### PR TITLE
Made core/main PEP8 compliant. Added requirements file.

### PR DESCRIPTION
**Pull request by aule**
All files have 4 space indentation now (previous was mix of tab and 2 space)

Made one file (core/main) compliant so far:
* 80 line length done using parenthesis blocks. 
* Multiline text done using the dedent function. 
* String concatination replaced with the format method. 
* Many whitespace errors corrected.

Also added basic support for virtualenv, which was required to test locally.
Setup for development can now be done with:
  virtualenv -ppython3 env
  . env/bin/activate
  pip install -r requirements.txt

### CODE REVIEW

**Comment by cosmosquark** [comment]
Will review these changes properly tonight (working on my PhD thesis). I can't see why this won't be accepted though. Good job!

**Comment by cosmosquark** [comment]
Looking over the changes, they all seem good. @aule I am happy to accept this PR once @staircase27 comments and mine have been addressed.

**Comment by staircase27** [comment]
Looking good. Thanks for the help joe. I've not had time to be careful when writing this so good to have it tidied up. :D

**Comment by staircase27** [comment]
Joe are you going to make the last few edits for multiplexer or shall I?

**Comment by aule** [comment]
All the changes should be in the last commit. I added a missing line to it
this morning.

**Comment by cosmosquark** [comment]
With the latest commit, it looks like we are ready to accept this PR. Unless @staircase27 thinks otherwise, I shall accept the PR tomorrow.

**Review by cosmosquark — APPROVED** [review]

**Pull request merged**
